all:
  hosts:
    mk-vps-0002:
      ansible_host: 160.251.169.69
      ansible_user: root
      ansible_password: mkVps0002@root
    mk-vps-0003:
      ansible_host: 163.44.97.146
      ansible_user: root
      ansible_password: mkVps0003@root
      